version: '3.8'

services:
  mongo:
    image: mongo:5.0.6-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: taki-dev-db
    ports:
      - '27017:27017'
    networks:
      - app-mongo
    restart: always

networks:
  app-mongo:
    driver: bridge
